[package]
name = "flag_symmetry"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
bytes = "1.1.0"  
tokio = { version = "1", features = ["full"] }
image = "0.25.1"
colored = "2.1.0"
