use std::collections::HashMap;
use lazy_static::lazy_static;

lazy_static! {
    pub static ref COUNTRIES: HashMap<&'static str, &'static str> = {
        let mut m = HashMap::new();
        m.insert("ad", "Andorra");
        m.insert("ae", "United Arab Emirates");
        m.insert("af", "Afghanistan");
        m.insert("ag", "Antigua and Barbuda");
        m.insert("ai", "Anguilla");
        m.insert("al", "Albania");
        m.insert("am", "Armenia");
        m.insert("ao", "Angola");
        m.insert("aq", "Antarctica");
        m.insert("ar", "Argentina");
        m.insert("as", "American Samoa");
        m.insert("at", "Austria");
        m.insert("au", "Australia");
        m.insert("aw", "Aruba");
        m.insert("ax", "Åland Islands");
        m.insert("az", "Azerbaijan");
        m.insert("ba", "Bosnia and Herzegovina");
        m.insert("bb", "Barbados");
        m.insert("bd", "Bangladesh");
        m.insert("be", "Belgium");
        m.insert("bf", "Burkina Faso");
        m.insert("bg", "Bulgaria");
        m.insert("bh", "Bahrain");
        m.insert("bi", "Burundi");
        m.insert("bj", "Benin");
        m.insert("bl", "Saint Barthélemy");
        m.insert("bm", "Bermuda");
        m.insert("bn", "Brunei");
        m.insert("bo", "Bolivia");
        m.insert("bq", "Caribbean Netherlands");
        m.insert("br", "Brazil");
        m.insert("bs", "Bahamas");
        m.insert("bt", "Bhutan");
        m.insert("bv", "Bouvet Island");
        m.insert("bw", "Botswana");
        m.insert("by", "Belarus");
        m.insert("bz", "Belize");
        m.insert("ca", "Canada");
        m.insert("cc", "Cocos (Keeling) Islands");
        m.insert("cd", "DR Congo");
        m.insert("cf", "Central African Republic");
        m.insert("cg", "Republic of the Congo");
        m.insert("ch", "Switzerland");
        m.insert("ci", "Côte d'Ivoire (Ivory Coast)");
        m.insert("ck", "Cook Islands");
        m.insert("cl", "Chile");
        m.insert("cm", "Cameroon");
        m.insert("cn", "China");
        m.insert("co", "Colombia");
        m.insert("cr", "Costa Rica");
        m.insert("cu", "Cuba");
        m.insert("cv", "Cape Verde");
        m.insert("cw", "Curaçao");
        m.insert("cx", "Christmas Island");
        m.insert("cy", "Cyprus");
        m.insert("cz", "Czechia");
        m.insert("de", "Germany");
        m.insert("dj", "Djibouti");
        m.insert("dk", "Denmark");
        m.insert("dm", "Dominica");
        m.insert("do", "Dominican Republic");
        m.insert("dz", "Algeria");
        m.insert("ec", "Ecuador");
        m.insert("ee", "Estonia");
        m.insert("eg", "Egypt");
        m.insert("eh", "Western Sahara");
        m.insert("er", "Eritrea");
        m.insert("es", "Spain");
        m.insert("et", "Ethiopia");
        m.insert("eu", "European Union");
        m.insert("fi", "Finland");
        m.insert("fj", "Fiji");
        m.insert("fk", "Falkland Islands");
        m.insert("fm", "Micronesia");
        m.insert("fo", "Faroe Islands");
        m.insert("fr", "France");
        m.insert("ga", "Gabon");
        m.insert("gb", "United Kingdom");
        m.insert("gb-eng", "England");
        m.insert("gb-nir", "Northern Ireland");
        m.insert("gb-sct", "Scotland");
        m.insert("gb-wls", "Wales");
        m.insert("gd", "Grenada");
        m.insert("ge", "Georgia");
        m.insert("gf", "French Guiana");
        m.insert("gg", "Guernsey");
        m.insert("gh", "Ghana");
        m.insert("gi", "Gibraltar");
        m.insert("gl", "Greenland");
        m.insert("gm", "Gambia");
        m.insert("gn", "Guinea");
        m.insert("gp", "Guadeloupe");
        m.insert("gq", "Equatorial Guinea");
        m.insert("gr", "Greece");
        m.insert("gs", "South Georgia");
        m.insert("gt", "Guatemala");
        m.insert("gu", "Guam");
        m.insert("gw", "Guinea-Bissau");
        m.insert("gy", "Guyana");
        m.insert("hk", "Hong Kong");
        m.insert("hm", "Heard Island and McDonald Islands");
        m.insert("hn", "Honduras");
        m.insert("hr", "Croatia");
        m.insert("ht", "Haiti");
        m.insert("hu", "Hungary");
        m.insert("id", "Indonesia");
        m.insert("ie", "Ireland");
        m.insert("il", "Israel");
        m.insert("im", "Isle of Man");
        m.insert("in", "India");
        m.insert("io", "British Indian Ocean Territory");
        m.insert("iq", "Iraq");
        m.insert("ir", "Iran");
        m.insert("is", "Iceland");
        m.insert("it", "Italy");
        m.insert("je", "Jersey");
        m.insert("jm", "Jamaica");
        m.insert("jo", "Jordan");
        m.insert("jp", "Japan");
        m.insert("ke", "Kenya");
        m.insert("kg", "Kyrgyzstan");
        m.insert("kh", "Cambodia");
        m.insert("ki", "Kiribati");
        m.insert("km", "Comoros");
        m.insert("kn", "Saint Kitts and Nevis");
        m.insert("kp", "North Korea");
        m.insert("kr", "South Korea");
        m.insert("kw", "Kuwait");
        m.insert("ky", "Cayman Islands");
        m.insert("kz", "Kazakhstan");
        m.insert("la", "Laos");
        m.insert("lb", "Lebanon");
        m.insert("lc", "Saint Lucia");
        m.insert("li", "Liechtenstein");
        m.insert("lk", "Sri Lanka");
        m.insert("lr", "Liberia");
        m.insert("ls", "Lesotho");
        m.insert("lt", "Lithuania");
        m.insert("lu", "Luxembourg");
        m.insert("lv", "Latvia");
        m.insert("ly", "Libya");
        m.insert("ma", "Morocco");
        m.insert("mc", "Monaco");
        m.insert("md", "Moldova");
        m.insert("me", "Montenegro");
        m.insert("mf", "Saint Martin");
        m.insert("mg", "Madagascar");
        m.insert("mh", "Marshall Islands");
        m.insert("mk", "North Macedonia");
        m.insert("ml", "Mali");
        m.insert("mm", "Myanmar");
        m.insert("mn", "Mongolia");
        m.insert("mo", "Macau");
        m.insert("mp", "Northern Mariana Islands");
        m.insert("mq", "Martinique");
        m.insert("mr", "Mauritania");
        m.insert("ms", "Montserrat");
        m.insert("mt", "Malta");
        m.insert("mu", "Mauritius");
        m.insert("mv", "Maldives");
        m.insert("mw", "Malawi");
        m.insert("mx", "Mexico");
        m.insert("my", "Malaysia");
        m.insert("mz", "Mozambique");
        m.insert("na", "Namibia");
        m.insert("nc", "New Caledonia");
        m.insert("ne", "Niger");
        m.insert("nf", "Norfolk Island");
        m.insert("ng", "Nigeria");
        m.insert("ni", "Nicaragua");
        m.insert("nl", "Netherlands");
        m.insert("no", "Norway");
        m.insert("np", "Nepal");
        m.insert("nr", "Nauru");
        m.insert("nu", "Niue");
        m.insert("nz", "New Zealand");
        m.insert("om", "Oman");
        m.insert("pa", "Panama");
        m.insert("pe", "Peru");
        m.insert("pf", "French Polynesia");
        m.insert("pg", "Papua New Guinea");
        m.insert("ph", "Philippines");
        m.insert("pk", "Pakistan");
        m.insert("pl", "Poland");
        m.insert("pm", "Saint Pierre and Miquelon");
        m.insert("pn", "Pitcairn Islands");
        m.insert("pr", "Puerto Rico");
        m.insert("ps", "Palestine");
        m.insert("pt", "Portugal");
        m.insert("pw", "Palau");
        m.insert("py", "Paraguay");
        m.insert("qa", "Qatar");
        m.insert("re", "Réunion");
        m.insert("ro", "Romania");
        m.insert("rs", "Serbia");
        m.insert("ru", "Russia");
        m.insert("rw", "Rwanda");
        m.insert("sa", "Saudi Arabia");
        m.insert("sb", "Solomon Islands");
        m.insert("sc", "Seychelles");
        m.insert("sd", "Sudan");
        m.insert("se", "Sweden");
        m.insert("sg", "Singapore");
        m.insert("sh", "Saint Helena, Ascension and Tristan da Cunha");
        m.insert("si", "Slovenia");
        m.insert("sj", "Svalbard and Jan Mayen");
        m.insert("sk", "Slovakia");
        m.insert("sl", "Sierra Leone");
        m.insert("sm", "San Marino");
        m.insert("sn", "Senegal");
        m.insert("so", "Somalia");
        m.insert("sr", "Suriname");
        m.insert("ss", "South Sudan");
        m.insert("st", "São Tomé and Príncipe");
        m.insert("sv", "El Salvador");
        m.insert("sx", "Sint Maarten");
        m.insert("sy", "Syria");
        m.insert("sz", "Eswatini (Swaziland)");
        m.insert("tc", "Turks and Caicos Islands");
        m.insert("td", "Chad");
        m.insert("tf", "French Southern and Antarctic Lands");
        m.insert("tg", "Togo");
        m.insert("th", "Thailand");
        m.insert("tj", "Tajikistan");
        m.insert("tk", "Tokelau");
        m.insert("tl", "Timor-Leste");
        m.insert("tm", "Turkmenistan");
        m.insert("tn", "Tunisia");
        m.insert("to", "Tonga");
        m.insert("tr", "Turkey");
        m.insert("tt", "Trinidad and Tobago");
        m.insert("tv", "Tuvalu");
        m.insert("tw", "Taiwan");
        m.insert("tz", "Tanzania");
        m.insert("ua", "Ukraine");
        m.insert("ug", "Uganda");
        m.insert("um", "United States Minor Outlying Islands");
        m.insert("un", "United Nations");
        m.insert("us", "United States");
        m.insert("us-ak", "Alaska");
        m.insert("us-al", "Alabama");
        m.insert("us-ar", "Arkansas");
        m.insert("us-az", "Arizona");
        m.insert("us-ca", "California");
        m.insert("us-co", "Colorado");
        m.insert("us-ct", "Connecticut");
        m.insert("us-de", "Delaware");
        m.insert("us-fl", "Florida");
        m.insert("us-ga", "Georgia");
        m.insert("us-hi", "Hawaii");
        m.insert("us-ia", "Iowa");
        m.insert("us-id", "Idaho");
        m.insert("us-il", "Illinois");
        m.insert("us-in", "Indiana");
        m.insert("us-ks", "Kansas");
        m.insert("us-ky", "Kentucky");
        m.insert("us-la", "Louisiana");
        m.insert("us-ma", "Massachusetts");
        m.insert("us-md", "Maryland");
        m.insert("us-me", "Maine");
        m.insert("us-mi", "Michigan");
        m.insert("us-mn", "Minnesota");
        m.insert("us-mo", "Missouri");
        m.insert("us-ms", "Mississippi");
        m.insert("us-mt", "Montana");
        m.insert("us-nc", "North Carolina");
        m.insert("us-nd", "North Dakota");
        m.insert("us-ne", "Nebraska");
        m.insert("us-nh", "New Hampshire");
        m.insert("us-nj", "New Jersey");
        m.insert("us-nm", "New Mexico");
        m.insert("us-nv", "Nevada");
        m.insert("us-ny", "New York");
        m.insert("us-oh", "Ohio");
        m.insert("us-ok", "Oklahoma");
        m.insert("us-or", "Oregon");
        m.insert("us-pa", "Pennsylvania");
        m.insert("us-ri", "Rhode Island");
        m.insert("us-sc", "South Carolina");
        m.insert("us-sd", "South Dakota");
        m.insert("us-tn", "Tennessee");
        m.insert("us-tx", "Texas");
        m.insert("us-ut", "Utah");
        m.insert("us-va", "Virginia");
        m.insert("us-vt", "Vermont");
        m.insert("us-wa", "Washington");
        m.insert("us-wi", "Wisconsin");
        m.insert("us-wv", "West Virginia");
        m.insert("us-wy", "Wyoming");
        m.insert("uy", "Uruguay");
        m.insert("uz", "Uzbekistan");
        m.insert("va", "Vatican City (Holy See)");
        m.insert("vc", "Saint Vincent and the Grenadines");
        m.insert("ve", "Venezuela");
        m.insert("vg", "British Virgin Islands");
        m.insert("vi", "United States Virgin Islands");
        m.insert("vn", "Vietnam");
        m.insert("vu", "Vanuatu");
        m.insert("wf", "Wallis and Futuna");
        m.insert("ws", "Samoa");
        m.insert("xk", "Kosovo");
        m.insert("ye", "Yemen");
        m.insert("yt", "Mayotte");
        m.insert("za", "South Africa");
        m.insert("zm", "Zambia");
        m.insert("zw", "Zimbabwe");
        m
    };
}
